# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fBwDB_YiGjqQzbep5DTZCgB382VPhla
"""

from google.colab import userdata
os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')

client = OpenAI()

!pip install -q openai pandas numpy faiss-cpu sentence-transformers openpyxl

import os
import json
import pandas as pd
import numpy as np
import faiss
from openai import OpenAI
from sentence_transformers import SentenceTransformer

import pandas as pd

excel_path = "/content/PriceWise_AI_Final_Strategy_Model.xlsx"

xls = pd.ExcelFile(excel_path)

print("Sheet names:")
for sheet in xls.sheet_names:
    print("-", sheet)

excel_path = "PriceWise_AI_Final_Strategy_Model.xlsx"

market_data = pd.read_excel(excel_path, sheet_name="market_data")
pricing_knowledge = pd.read_excel(excel_path, sheet_name="pricing_knowledge")
strategic_knowledge = pd.read_excel(excel_path, sheet_name="strategic_knowledge_seed")
management_frameworks = pd.read_excel(excel_path, sheet_name="management_frameworks_final")
strategy_matrix = pd.read_excel(excel_path, sheet_name="strategy_decision_matrix")
framework_router = pd.read_excel(excel_path, sheet_name="framework_router_final")
rbv_vrio = pd.read_excel(excel_path, sheet_name="rbv_vrio_assessment")
fmea = pd.read_excel(excel_path, sheet_name="fmea_risk_template")

print("All main sheets loaded successfully.")

sheets = {
    "market_data": market_data,
    "pricing_knowledge": pricing_knowledge,
    "strategic_knowledge": strategic_knowledge,
    "management_frameworks": management_frameworks,
    "strategy_matrix": strategy_matrix,
    "framework_router": framework_router,
    "rbv_vrio": rbv_vrio,
    "fmea": fmea
}

for name, df in sheets.items():
    print("\n" + "="*50)
    print(name)
    print(df.columns.tolist())
    print(df.shape)

market_data.head()

pricing_knowledge.head()

strategic_knowledge.head()

management_frameworks.head()

# preprocessing
for name in sheets:
    sheets[name] = sheets[name].dropna(how="all").reset_index(drop=True)

market_data = sheets["market_data"]
pricing_knowledge = sheets["pricing_knowledge"]
strategic_knowledge = sheets["strategic_knowledge"]
management_frameworks = sheets["management_frameworks"]
strategy_matrix = sheets["strategy_matrix"]
framework_router = sheets["framework_router"]
rbv_vrio = sheets["rbv_vrio"]
fmea = sheets["fmea"]

# RAG
rag_documents = []
def add_documents_from_df(df, source_name):
    for i, row in df.iterrows():
        row_text = []
        for col in df.columns:
            value = row[col]
            if pd.notna(value):
                row_text.append(f"{col}: {value}")
        text = "\n".join(row_text)

        if len(text.strip()) > 20:
            rag_documents.append({
                "source": source_name,
                "row": i,
                "text": text
            })
add_documents_from_df(pricing_knowledge, "pricing_knowledge")
add_documents_from_df(strategic_knowledge, "strategic_knowledge_seed")
add_documents_from_df(management_frameworks, "management_frameworks_final")
add_documents_from_df(strategy_matrix, "strategy_decision_matrix")

print("Number of RAG documents:", len(rag_documents))
print("\nSample document:\n")
print(rag_documents[0]["text"])

from sentence_transformers import SentenceTransformer
import numpy as np
import faiss

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
texts = [doc["text"] for doc in rag_documents]

print("Number of texts:", len(texts))
print(texts[0])
embeddings = embedding_model.encode(texts, convert_to_numpy=True)

print("Embedding shape:", embeddings.shape)

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(embeddings)

print("FAISS index created.")
print("Number of vectors in index:", index.ntotal)

# test
query = "My competitors are cheaper. Which pricing strategy should I use?"

query_embedding = embedding_model.encode([query], convert_to_numpy=True)

distances, indices = index.search(query_embedding, 3)

for idx in indices[0]:
    print("="*50)
    print("Source:", rag_documents[idx]["source"])
    print("Row:", rag_documents[idx]["row"])
    print(rag_documents[idx]["text"])

def retrieval_agent(query, top_k=4):
    query_embedding = embedding_model.encode([query], convert_to_numpy=True)

    distances, indices = index.search(query_embedding, top_k)

    retrieved_docs = []

    for rank, idx in enumerate(indices[0]):
        retrieved_docs.append({
            "rank": rank + 1,
            "source": rag_documents[idx]["source"],
            "row": rag_documents[idx]["row"],
            "text": rag_documents[idx]["text"],
            "distance": float(distances[0][rank])
        })

    return retrieved_docs

def format_retrieved_docs(retrieved_docs):
    formatted_text = ""

    for doc in retrieved_docs:
        formatted_text += f"""
Retrieved Document {doc['rank']}
Source: {doc['source']}
Row: {doc['row']}
Content:
{doc['text']}

"""

    return formatted_text

test_query = "My competitors are cheaper. Which pricing strategy should I use?"

results = retrieval_agent(test_query, top_k=4)

for doc in results:
    print("="*50)
    print("Rank:", doc["rank"])
    print("Source:", doc["source"])
    print("Row:", doc["row"])
    print("Distance:", doc["distance"])
    print(doc["text"])

retrieved_context = format_retrieved_docs(results)

print(retrieved_context)

user_question = "My competitors are cheaper. Which pricing strategy should I use?"

retrieved_docs = retrieval_agent(user_question, top_k=4)
retrieved_context = format_retrieved_docs(retrieved_docs)

prompt = f"""
You are PriceWise AI, an Agentic RAG-based pricing strategy advisor.

User question:
{user_question}

Retrieved knowledge from the pricing and strategy knowledge base:
{retrieved_context}

Your task:
Answer the user's question using only the retrieved knowledge and practical pricing reasoning.

Structure your answer as:
1. Diagnosis
2. Recommended pricing strategy
3. Why this strategy fits
4. Risks
5. Final recommendation
"""

print(prompt)

def format_retrieved_docs(retrieved_docs):
    formatted_text = ""

    for doc in retrieved_docs:
        formatted_text += f"""
Retrieved Document {doc['rank']}
Source: {doc['source']}
Row: {doc['row']}
Distance: {doc['distance']}
Content:
{doc['text']}

"""

    return formatted_text

retrieved_context = format_retrieved_docs(results)

print(retrieved_context)

user_question = "My competitors are cheaper. Which pricing strategy should I use?"

retrieved_docs = retrieval_agent(user_question, top_k=4)

retrieved_context = format_retrieved_docs(retrieved_docs)

prompt = f"""
You are PriceWise AI, an Agentic RAG-based pricing strategy advisor.

User question:
{user_question}

Retrieved knowledge from the pricing and strategy knowledge base:
{retrieved_context}

Your task:
Answer the user's question using the retrieved knowledge and practical pricing reasoning.

Structure your answer as:
1. Pricing problem diagnosis
2. Competitor and substitute analysis
3. Recommended pricing strategy
4. Why this strategy fits
5. Risks
6. Final recommendation

Important rules:
- Use the retrieved knowledge.
- Do not make unrealistic promises.
- If information is missing, clearly mention what is missing.
- Be practical for small businesses.
"""

print(prompt)

print(client)

!pip install -q google-generativeai

import google.generativeai as genai
from getpass import getpass

GEMINI_API_KEY = getpass("Enter Gemini API Key: ")

genai.configure(api_key=GEMINI_API_KEY)

print("Gemini configured successfully.")

import google.generativeai as genai

genai.configure(api_key='AIzaSyARNBXX3gGVRKyphhvA9QBHsfJOpa9Y5hc')

model = genai.GenerativeModel("models/gemini-2.5-flash")

print("Gemini model is ready.")

while True:

    user_question = input("\nAsk your pricing question (type exit to stop): ")

    if user_question.lower() == "exit":
        print("PriceWise AI stopped.")
        break

    # =========================
    # Retrieval
    # =========================

    query_embedding = embedding_model.encode(
        [user_question],
        convert_to_numpy=True
    )

    distances, indices = index.search(query_embedding, 2)

    retrieved_context = ""

    for rank, idx in enumerate(indices[0]):

        retrieved_context += f"""
Document {rank+1}

{rag_documents[idx]['text'][:500]}

"""

    # =========================
    # Small Prompt
    # =========================

    prompt = f"""
You are a pricing strategy advisor.

User Question:
{user_question}

Retrieved Knowledge:
{retrieved_context}

Answer briefly and professionally.

Include:
- Diagnosis
- Best pricing strategy
- Risks
- Recommendation
"""

    # =========================
    # Gemini
    # =========================

    response = model.generate_content(
        prompt
    )

    print("\n" + "="*60)
    print(response.text)
    print("="*60)

for m in genai.list_models():
    if "generateContent" in m.supported_generation_methods:
        print(m.name)